spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_DEFAULT_ZONE}
    register-with-eureka: false
    fetch-registry: false
