#spring:
#  application:
#    name: inventory-service
#  jpa:
#    hibernate:
#      ddl-auto: update
#      shw-sql: true
#server:
#  port: 8081
#
#  datasource:
#    url: jdbc:h2:mem:inventory-service
#    generate-unique-name: false
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  sql:
#    init:
#      platform: h2
#
##eureka:
##  client:
##    defaultZone: http://localhost:8761/eureka/
##    enabled: true


spring:
  application:
    name: inventory-service

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: mysql
      schema-locations: classpath:create.sql

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_DEFAULT_ZONE}
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

server:
  port: 8081

