spring:
    application:
        name: spring-mail-async
    mail:
        port: 587
        test-connection: true
        protocol: smtp
        host: smtp.gmail.com
        username: sandeepgfgjava@gmail.com
        properties:
           mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true
                      required: true
server:
    port: 8085
