spring:
  application:
    name: user-service

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      registry-fetch-interval-seconds: 5
      initial-instance-info-replication-interval-seconds: 0
      fetch-registry: true
      instance:
        lease-renewal-interval-in-seconds: 5


server:
  port: 8082