
server:
  port: 8084


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: your_password
    url: jdbc:mysql://localhost:3306/test


  jpa:
    hibernate:
      ddl-auto: update
