spring:
    application:
        name: spring-rabbit
    rabbitmq:
        port: 5672

        host: localhost
        username: guest
        password: guest
        requested-heartbeat: 30
        connection-timeout: 30000
server:
    port: 8085
